#!/usr/bin/env node
/**
 * Sync version across Cargo.toml, app/package.json and app/src/version.ts.
 * - Source of truth: src-tauri/Cargo.toml [package.version]
 * - Updates root package.json (optional semantic alignment) and app/package.json
 * - Regenerates app/src/version.ts
 * Idempotent: runs safely if versions already match.
 */
import fs from 'node:fs';
import path from 'node:path';

const projectRoot = path.resolve(process.cwd());
const cargoPath = path.join(projectRoot, 'src-tauri', 'Cargo.toml');
const rootPkgPath = path.join(projectRoot, 'package.json');
const appPkgPath = path.join(projectRoot, 'app', 'package.json');
const versionTsPath = path.join(projectRoot, 'app', 'src', 'version.ts');

function readFile(p){ return fs.readFileSync(p, 'utf8'); }
function writeFile(p,c){ fs.writeFileSync(p, c, 'utf8'); }

function extractCargoVersion(toml){
  // Simple regex parse (avoid full TOML dependency just for one field)
  const match = toml.match(/^[ \t]*version\s*=\s*"([0-9A-Za-z._-]+)"/m);
  if(!match) throw new Error('Could not find version in Cargo.toml');
  return match[1];
}

function updateJsonVersion(pkgPath, newVersion) {
  const raw = readFile(pkgPath);
  let json;
  try { json = JSON.parse(raw); } catch(e){ throw new Error('Invalid JSON at ' + pkgPath); }
  const before = json.version;
  if(before === newVersion) {
    return { changed:false, before, after:before };
  }
  json.version = newVersion;
  writeFile(pkgPath, JSON.stringify(json, null, 2) + '\n');
  return { changed:true, before, after:newVersion };
}

function updateVersionTs(newVersion){
  const content = `// Auto-generated by sync-version.mjs\nexport const APP_VERSION = '${newVersion}';\n`;
  let changed = true;
  if(fs.existsSync(versionTsPath)) {
    const current = readFile(versionTsPath);
    if(current.trim() === content.trim()) changed = false;
  }
  if(changed) writeFile(versionTsPath, content);
  return { changed };
}

(function main(){
  console.log('[sync-version] Reading Cargo.toml');
  const cargoToml = readFile(cargoPath);
  const version = extractCargoVersion(cargoToml);
  console.log('[sync-version] Source version =', version);

  const rootRes = updateJsonVersion(rootPkgPath, version);
  console.log(`[sync-version] Root package.json: ${rootRes.changed ? 'updated' : 'no change'} (${rootRes.before} -> ${rootRes.after})`);

  const appRes = updateJsonVersion(appPkgPath, version);
  console.log(`[sync-version] App package.json: ${appRes.changed ? 'updated' : 'no change'} (${appRes.before} -> ${appRes.after})`);

  const tsRes = updateVersionTs(version);
  console.log(`[sync-version] version.ts: ${tsRes.changed ? 'updated' : 'no change'}`);

  console.log('[sync-version] DONE');
})();
